:- encoding(utf8).
% index.pl — the index of 'Flora Excursoria Hafniensis' (Copenhagen, 1838)
%
% entry(Name, Page, Language).
%   Language is la (Latin) or da (Danish).
%
% Names and page numbers are transcribed from the index of the first edition
% (Kjøbenhavn 1838), in printed order and printed orthography. Nothing is
% corrected here. Corrections belong in flora.pl, as inferences, not as edits.
%
% 903 entries. 501 Latin, 402 Danish. 233 distinct pages, 1-320.

:- discontiguous entry/3.

entry('Aakande', 189, da).
entry('Abies', 305, la).
entry('Acer', 150, la).
entry('Achillæa', 270, la).
entry('Aconitum', 190, la).
entry('Acorus', 124, la).
entry('Actæa', 188, la).
entry('Adoxa', 153, la).
entry('Ægopodium', 115, la).
entry('Æthusa', 117, la).
entry('Aftenstjerne', 224, da).
entry('Agermaane', 171, da).
entry('Agrimonia', 171, la).
entry('Agropyrum', 47, la).
entry('Agrostemma', 166, la).
entry('Agrostis', 25, la).
entry('Aira', 32, la).
entry('Ajuga', 207, la).
entry('Akkeleie', 191, da).
entry('Alant', 268, da).
entry('Alchemilla', 52, la).
entry('Alectorolophus', 209, la).
entry('Alisma', 145, la).
entry('Allium', 136, la).
entry('Allosorus', 318, la).
entry('Alnus', 301, la).
entry('Alopecurus', 23, la).
entry('Alsine', 163, la).
entry('Alsinella', 163, la).
entry('Althæa', 232, la).
entry('Alyssum', 218, la).
entry('Ammophila', 28, la).
entry('Anagallis', 81, la).
entry('Anchusa', 75, la).
entry('Andemad', 2, da).
entry('Andromeda', 154, la).
entry('Anemone', 197, la).
entry('Angelica', 113, la).
entry('Antennaria', 265, la).
entry('Anthemis', 271, la).
entry('Anthericum', 136, la).
entry('Anthoxanthum', 29, la).
entry('Anthriscus', 109, la).
entry('Anthyllis', 236, la).
entry('Antirrhinum', 212, la).
entry('Apargia', 251, la).
entry('Apium', 115, la).
entry('Aqvilegia', 191, la).
entry('Arabis', 220, la).
entry('Aracium', 253, la).
entry('Arbutus', 155, la).
entry('Arctium', 259, la).
entry('Arctostaphylos', 155, la).
entry('Arenaria', 163, la).
entry('Armeria', 120, la).
entry('Armoracia', 220, la).
entry('Arnica', 267, la).
entry('Arrhenatherum', 30, la).
entry('Artemisia', 263, la).
entry('Arve', 81, da).
entry('Arum', 301, la).
entry('Arundo', 26, la).
entry('Asarum', 171, la).
entry('Asclepias', 108, la).
entry('Ask', 2, da).
entry('Asperugo', 74, la).
entry('Asperula', 58, la).
entry('Aspidium', 318, la).
entry('Asplenium', 315, la).
entry('Aster', 268, la).
entry('Asterocephalus', 56, la).
entry('Astragalus', 242, la).
entry('Athyrium', 316, la).
entry('Atriplex', 105, la).
entry('Avena', 30, la).
entry('Avenella', 32, la).
entry('Avl', 175, da).
entry('Avnbög', 301, da).
entry('Avnknippe', 15, da).
entry('Bakkestjerne', 269, da).
entry('Baldingera', 25, la).
entry('Baldrian', 11, da).
entry('Ballota', 205, la).
entry('Balsamin', 97, da).
entry('Barbaræa', 223, la).
entry('Barsvælg', 204, da).
entry('Bartschia', 211, la).
entry('Bede', 105, da).
entry('Beenved', 62, da).
entry('Bellis', 269, la).
entry('Berberis', 138, la).
entry('Berle', 116, da).
entry('Berula', 116, la).
entry('Beta', 105, la).
entry('Betonica', 202, la).
entry('Betula', 304, la).
entry('Bidens', 262, la).
entry('Bingelurt', 313, da).
entry('Birk', 304, da).
entry('Bittermælk', 252, da).
entry('Björneklo', 113, da).
entry('Blaabær', 147, da).
entry('Blaastjerne', 57, da).
entry('Bladhoved', 260, da).
entry('Blechnum', 318, la).
entry('Blitum', 104, la).
entry('Blysmus', 15, la).
entry('Blærerod', 4, da).
entry('Boghvede', 152, da).
entry('Borago', 75, la).
entry('Borst', 251, da).
entry('Botrychium', 319, la).
entry('Braadfrö', 305, da).
entry('Brachyolobus', 220, la).
entry('Brachypodium', 46, la).
entry('Brandbæger', 265, da).
entry('Brassica', 226, la).
entry('Bridurt', 99, da).
entry('Briza', 33, la).
entry('Bromochloa', 43, la).
entry('Bromus', 37, la).
entry('Brudelys', 154, da).
entry('Brunrod', 213, da).
entry('Bryonia', 306, la).
entry('Brændeskjærm', 116, da).
entry('Bröndkarse', 224, da).
entry('Bröndsel', 262, da).
entry('Bukkeblad', 88, da).
entry('Bulliarda', 71, la).
entry('Bulme', 87, da).
entry('Bunias', 216, la).
entry('Bunke', 32, da).
entry('Bunkehavre', 32, da).
entry('Buplevrum', 114, la).
entry('Burre', 259, da).
entry('Busmekker', 115, da).
entry('Byg', 50, da).
entry('Bynke', 263, da).
entry('Bægerbrægne', 316, da).
entry('Bændeltang', 281, da).
entry('Bævregræs', 33, da).
entry('Bög', 304, da).
entry('Börsteax', 51, da).
entry('Cakile', 215, la).
entry('Calamintha', 206, la).
entry('Calla', 281, la).
entry('Callitriche', 281, la).
entry('Calluna', 146, la).
entry('Caltha', 198, la).
entry('Camelina', 221, la).
entry('Campanula', 91, la).
entry('Cannabis', 311, la).
entry('Capsella', 218, la).
entry('Cardamine', 222, la).
entry('Carlina', 258, la).
entry('Carduus', 261, la).
entry('Carex', 284, la).
entry('Carpinus', 304, la).
entry('Carum', 115, la).
entry('Catabrosa', 39, la).
entry('Caucalis', 109, la).
entry('Centaurea', 271, la).
entry('Centinodium', 151, la).
entry('Centunculus', 55, la).
entry('Cephalanthera', 277, la).
entry('Cerastium', 167, la).
entry('Cerasus', 173, la).
entry('Ceratophyllum', 303, la).
entry('Chærophyllum', 111, la).
entry('Chamænerium', 148, la).
entry('Chamæplium', 225, la).
entry('Chelidonium', 187, la).
entry('Chenopodium', 100, la).
entry('Chrysanthemum', 269, la).
entry('Chrysosplenium', 157, la).
entry('Cichorium', 251, la).
entry('Cicuta', 116, la).
entry('Cineraria', 267, la).
entry('Circæa', 3, la).
entry('Cirsium', 260, la).
entry('Cistus', 189, la).
entry('Cladium', 15, la).
entry('Clinopodium', 206, la).
entry('Cnidium', 116, la).
entry('Cochlearia', 219, la).
entry('Cochlidiosperma', 5, la).
entry('Codonoprasum', 137, la).
entry('Coeloglossum', 276, la).
entry('Comarum', 183, la).
entry('Conium', 112, la).
entry('Convallaria', 132, la).
entry('Convolvulus', 83, la).
entry('Corallorhiza', 277, la).
entry('Cornus', 62, la).
entry('Corylus', 304, la).
entry('Corydalis', 233, la).
entry('Corynephorus', 32, la).
entry('Corvisartia', 268, la).
entry('Cracca', 213, la).
entry('Crambe', 216, la).
entry('Cratægus', 174, la).
entry('Crepis', 252, la).
entry('Cuscuta', 62, la).
entry('Cynanchum', 108, la).
entry('Cynoglossum', 74, la).
entry('Cynosurus', 45, la).
entry('Cyperus', 14, la).
entry('Cystopteris', 316, la).
entry('Dactylis', 44, la).
entry('Datura', 86, la).
entry('Delphinium', 190, la).
entry('Dentaria', 223, la).
entry('Desmerurt', 153, da).
entry('Dianthus', 158, la).
entry('Dichostylis', 17, la).
entry('Digitalis', 212, la).
entry('Digraphis', 25, la).
entry('Dipsacus', 55, la).
entry('Dodder', 221, da).
entry('Draba', 218, la).
entry('Draphavre', 30, da).
entry('Drosera', 123, la).
entry('Druehyacinth', 134, da).
entry('Druemunke', 188, da).
entry('Dueurt', 148, da).
entry('Dunhammer', 284, da).
entry('Dyndurt', 213, da).
entry('Echinops', 272, la).
entry('Echinospermum', 74, la).
entry('Echium', 71, la).
entry('Edderkopurt', 137, da).
entry('Eeg', 304, da).
entry('Elatine', 152, la).
entry('Elsholzia', 201, la).
entry('Elymus', 50, la).
entry('Empetrum', 310, la).
entry('Ene', 311, da).
entry('Engblomme', 198, da).
entry('Engelsöd', 314, da).
entry('Enodium', 40, la).
entry('Entian', 88, da).
entry('Epigogium', 280, la).
entry('Epilobium', 148, la).
entry('Epipactis', 279, la).
entry('Eqvisetum', 320, la).
entry('Eranthis', 198, la).
entry('Erica', 146, la).
entry('Erigeron', 269, la).
entry('Eriophorum', 18, la).
entry('Erodium', 227, la).
entry('Eryngium', 119, la).
entry('Erysimum', 224, la).
entry('Erythræa', 89, la).
entry('Esparsette', 242, da).
entry('Euonymus', 62, la).
entry('Eupatorium', 261, la).
entry('Euphorbia', 283, la).
entry('Euphrasia', 210, la).
entry('Evighedsblomst', 265, da).
entry('Faareleger', 120, da).
entry('Fagopyrum', 152, la).
entry('Fagus', 301, la).
entry('Fedia', 12, la).
entry('Femling', 169, da).
entry('Festgræs', 29, da).
entry('Festuca', 41, la).
entry('Ficaria', 191, la).
entry('Fiirblad', 153, da).
entry('Fiirling', 170, da).
entry('Filago', 264, la).
entry('Fladax', 14, da).
entry('Fladbælle', 245, da).
entry('Fladknap', 272, da).
entry('Fladstjerne', 161, da).
entry('Fliglæbe', 276, da).
entry('Flipkrave', 216, da).
entry('Flitterax', 33, da).
entry('Fnokurt', 267, da).
entry('Fodangel', 109, da).
entry('Foldfrö', 112, da).
entry('Forgjetmigei', 76, da).
entry('Fragaria', 183, la).
entry('Fraxinus', 2, la).
entry('Fredlös', 81, da).
entry('Fritillaria', 134, la).
entry('Fröbid', 313, da).
entry('Fröstjerne', 195, da).
entry('Fugleklo', 242, da).
entry('Fugleknude', 151, da).
entry('Fugleliim', 310, da).
entry('Fuglemælk', 136, da).
entry('Fuglerede', 278, da).
entry('Fumaria', 232, la).
entry('Fyr', 305, da).
entry('Fölfod', 263, da).
entry('Gaasefod', 100, da).
entry('Gaasemad', 222, da).
entry('Gabeklap', 225, da).
entry('Gagea', 134, la).
entry('Galanthus', 133, la).
entry('Galdebær', 306, da).
entry('Galeobdolon', 204, la).
entry('Galeopsis', 201, la).
entry('Galium', 58, la).
entry('Galtetand', 202, da).
entry('Gedeblad', 93, da).
entry('Gederams', 148, da).
entry('Gedeskjæg', 258, da).
entry('Gentiana', 88, la).
entry('Geranium', 227, la).
entry('Geum', 186, la).
entry('Gifttyde', 116, da).
entry('Gjæslingblomst', 218, da).
entry('Gjögemad', 230, da).
entry('Gjögeurt', 273, da).
entry('Glaux', 83, la).
entry('Glechoma', 203, la).
entry('Glyceria', 40, la).
entry('Gnaphalium', 265, la).
entry('Godtraad', 145, da).
entry('Gran', 305, da).
entry('Gulddusk', 83, da).
entry('Guldstjerne', 134, da).
entry('Gulerod', 112, da).
entry('Guulax', 29, da).
entry('Gyclqvæler', 214, da).
entry('Gyldenriis', 268, da).
entry('Gymnadenia', 275, la).
entry('Gypsophila', 159, la).
entry('Gypsurt', 159, da).
entry('Gyvel', 235, da).
entry('Habenaria', 277, la).
entry('Halianthus', 163, la).
entry('Halimus', 108, la).
entry('Halvsvöb', 117, da).
entry('Hamp', 311, da).
entry('Hanekro', 201, da).
entry('Haremad', 251, da).
entry('Hareöre', 114, da).
entry('Hassel', 304, da).
entry('Havre', 30, da).
entry('Havtorn', 174, da).
entry('Hedera', 98, la).
entry('Hedysarum', 242, la).
entry('Heire', 37, da).
entry('Heleocharis', 16, la).
entry('Heleochloa', 39, la).
entry('Heleogeton', 20, la).
entry('Helianthemum', 189, la).
entry('Helichrysum', 265, la).
entry('Helleborus', 198, la).
entry('Helosciadum', 114, la).
entry('Hepatica', 197, la).
entry('Heracleum', 113, la).
entry('Herminium', 276, la).
entry('Herniaria', 99, la).
entry('Hesperis', 224, la).
entry('Hestegræs', 29, da).
entry('Hestehov', 262, da).
entry('Hieracium', 254, la).
entry('Hierochloa', 29, la).
entry('Himantoglossum', 276, la).
entry('Hippochæris', 255, la).
entry('Hippophae', 311, la).
entry('Hippuris', 1, la).
entry('Hjertelæbe', 280, da).
entry('Hjertespand', 205, da).
entry('Hjorterod', 118, da).
entry('Hjortetröst', 261, da).
entry('Hjælme', 28, da).
entry('Hjörneklap', 224, da).
entry('Holcus', 29, la).
entry('Holosteum', 52, la).
entry('Hordeum', 50, la).
entry('Hornblad', 303, da).
entry('Hottonia', 81, la).
entry('Humle', 311, da).
entry('Humulus', 311, la).
entry('Hundegræs', 44, da).
entry('Hundetunge', 74, da).
entry('Huullæbe', 247, da).
entry('Huulsvöb', 111, da).
entry('Hvene', 25, da).
entry('Hyacinthus', 134, la).
entry('Hydrochæris', 313, la).
entry('Hydrocotyle', 118, la).
entry('Hyld', 119, da).
entry('Hyoscyamus', 87, la).
entry('Hypericum', 248, la).
entry('Hyrdetaske', 218, da).
entry('Hængeblomst', 257, da).
entry('Högeskjæg', 252, da).
entry('Högeurt', 254, da).
entry('Hönsetarm', 167, da).
entry('Hör', 123, da).
entry('Hörsilke', 62, da).
entry('Jacobsurt', 266, da).
entry('Jacobæa', 266, la).
entry('Jasione', 90, la).
entry('Jernurt', 208, da).
entry('Impatiens', 97, la).
entry('Inula', 268, la).
entry('Jordbær', 183, da).
entry('Jordrög', 232, da).
entry('Iris', 13, la).
entry('Isolepis', 20, la).
entry('Juncus', 126, la).
entry('Juniperus', 311, la).
entry('Kaal', 221, da).
entry('Kabbeleie', 198, da).
entry('Kalaminthe', 206, da).
entry('Kalmus', 124, da).
entry('Kamgræs', 45, da).
entry('Kamille', 271, da).
entry('Kamlöv', 318, da).
entry('Kantbælle', 241, da).
entry('Kantfrö', 17, da).
entry('Karline', 258, da).
entry('Karse', 217, da).
entry('Kartebolle', 55, da).
entry('Katost', 231, da).
entry('Kattefod', 265, da).
entry('Kattehale', 170, da).
entry('Katteurt', 203, da).
entry('Kiddike', 221, da).
entry('Kilebæger', 47, da).
entry('Kirsebærtræ', 173, da).
entry('Kjællingtand', 240, da).
entry('Kjæruld', 18, da).
entry('Klaseskjærm', 117, da).
entry('Klinte', 166, da).
entry('Klokke', 91, da).
entry('Klynger', 179, da).
entry('Klöftnaal', 216, da).
entry('Klöver', 236, da).
entry('Klövkrone', 167, da).
entry('Knavel', 157, da).
entry('Knopurt', 271, da).
entry('Knælæbe', 280, da).
entry('Kobjælde', 197, da).
entry('Kochia', 100, la).
entry('Kodriver', 79, da).
entry('Koeleria', 32, la).
entry('Koföde', 209, da).
entry('Kogleax', 19, da).
entry('Kokleare', 219, da).
entry('Kommen', 115, da).
entry('Kongebrægne', 318, da).
entry('Kongelys', 84, da).
entry('Kongepen', 255, da).
entry('Konval', 132, da).
entry('Koralrod', 277, da).
entry('Korneel', 62, da).
entry('Korsknop', 203, da).
entry('Kortlæbe', 207, da).
entry('Kortnæb', 111, da).
entry('Kortskulpe', 220, da).
entry('Kragefod', 183, da).
entry('Krageklo', 235, da).
entry('Krandsbörste', 206, da).
entry('Krap', 61, da).
entry('Krebsklo', 313, da).
entry('Krognaal', 218, da).
entry('Krop', 12, da).
entry('Kræge', 172, da).
entry('Krækling', 310, da).
entry('Kulsukker', 76, da).
entry('Körvel', 109, da).
entry('Lactuca', 256, la).
entry('Lamium', 203, la).
entry('Langnæb', 109, da).
entry('Lappa', 259, la).
entry('Lapsana', 250, la).
entry('Larix', 305, la).
entry('Laserpitium', 112, la).
entry('Lastrea', 317, la).
entry('Lathræa', 214, la).
entry('Lathyrus', 245, la).
entry('Lemna', 2, la).
entry('Leontodon', 256, la).
entry('Leonurus', 205, la).
entry('Lepidium', 217, la).
entry('Lepturus', 51, la).
entry('Leverurt', 120, da).
entry('Levisticum', 111, la).
entry('Libanotis', 118, la).
entry('Ligusticum', 114, la).
entry('Limnochloa', 18, la).
entry('Limonurt', 121, da).
entry('Limosella', 213, la).
entry('Linaria', 212, la).
entry('Lind', 189, da).
entry('Linum', 123, la).
entry('Listera', 278, la).
entry('Lithospermum', 72, la).
entry('Littorella', 302, la).
entry('Lobelia', 90, la).
entry('Lolium', 49, la).
entry('Lomaria', 318, la).
entry('Lonicera', 93, la).
entry('Loppeurt', 267, da).
entry('Lostilk', 114, da).
entry('Lotophyllum', 238, la).
entry('Lotus', 240, la).
entry('Lunaria', 218, la).
entry('Lungeurt', 73, da).
entry('Luzula', 175, la).
entry('Lychnis', 166, la).
entry('Lycopodium', 319, la).
entry('Lycopsis', 75, la).
entry('Lycopus', 4, la).
entry('Lyng', 146, da).
entry('Lysimachia', 81, la).
entry('Lythrum', 170, la).
entry('Læbelös', 207, da).
entry('Lærkespore', 233, da).
entry('Lærketræ', 305, da).
entry('Lög', 136, da).
entry('Lövefod', 52, da).
entry('Lövemule', 212, da).
entry('Lövetand', 256, da).
entry('Maanerude', 319, da).
entry('Majanthemum', 52, la).
entry('Maiblomst', 52, da).
entry('Malachium', 167, la).
entry('Malaxis', 280, la).
entry('Malus', 175, la).
entry('Malva', 231, la).
entry('Mandstro', 119, da).
entry('Mangelöv', 317, da).
entry('Marehalm', 50, da).
entry('Marietidsel', 259, da).
entry('Marrubium', 205, la).
entry('Matricaria', 270, la).
entry('Medicago', 241, la).
entry('Meelbær', 155, da).
entry('Melampyrum', 208, la).
entry('Melica', 33, la).
entry('Melilotus', 239, la).
entry('Mentha', 199, la).
entry('Menyanthes', 88, la).
entry('Mercurialis', 313, la).
entry('Merian', 201, da).
entry('Miliegræs', 28, da).
entry('Milium', 28, la).
entry('Miltbrægne', 316, da).
entry('Milturt', 157, da).
entry('Mjödurt', 174, da).
entry('Molinia', 40, la).
entry('Monotropa', 155, la).
entry('Montia', 51, la).
entry('Mosetot', 18, da).
entry('Munke', 90, da).
entry('Munkekrone', 270, da).
entry('Muscari', 134, la).
entry('Musehale', 124, da).
entry('Museurt', 264, da).
entry('Mycelis', 257, la).
entry('Mynte', 199, da).
entry('Myosotis', 76, la).
entry('Myosurus', 124, la).
entry('Myrica', 311, la).
entry('Myriophyllum', 303, la).
entry('Myrrhis', 111, la).
entry('Myrtillus', 147, la).
entry('Mysike', 58, da).
entry('Mysse', 281, da).
entry('Mælde', 105, da).
entry('Mælkurt', 231, da).
entry('Mærke', 116, da).
entry('Naalebæger', 99, da).
entry('Narcissus', 133, la).
entry('Nardus', 51, la).
entry('Nasturtium', 224, la).
entry('Natlys', 150, da).
entry('Natskygge', 87, da).
entry('Naumburgia', 83, la).
entry('Nellike', 158, da).
entry('Nellikerod', 186, da).
entry('Neottia', 278, la).
entry('Nepeta', 203, la).
entry('Neslia', 221, la).
entry('Norel', 163, da).
entry('Nuphar', 189, la).
entry('Nymphæa', 189, la).
entry('Nyserod', 198, da).
entry('Næbfrö', 15, da).
entry('Nælde', 302, da).
entry('Nöglekurv', 265, da).
entry('Nökkerose', 189, da).
entry('Odontites', 211, la).
entry('Oenanthe', 117, la).
entry('Oenothera', 150, la).
entry('Onobrychis', 242, la).
entry('Ononis', 235, la).
entry('Onopordon', 259, la).
entry('Ophioglossum', 319, la).
entry('Ophrys', 276, la).
entry('Orchis', 273, la).
entry('Origanum', 201, la).
entry('Ornithogalum', 136, la).
entry('Ornithopus', 242, la).
entry('Orobanche', 214, la).
entry('Orobus', 216, la).
entry('Osmunda', 318, la).
entry('Oxalis', 230, la).
entry('Oxetunge', 75, da).
entry('Oxeöie', 269, da).
entry('Oxycoccos', 147, la).
entry('Padderokke', 320, da).
entry('Panicum', 21, la).
entry('Papaver', 188, la).
entry('Paris', 153, la).
entry('Parietaria', 53, la).
entry('Parnassia', 120, la).
entry('Pastinaca', 113, la).
entry('Peberrod', 220, da).
entry('Pengeurt', 216, da).
entry('Peplis', 138, la).
entry('Perikon', 248, da).
entry('Petasites', 262, la).
entry('Peucedanum', 112, la).
entry('Phalaris', 25, la).
entry('Phellandrium', 118, la).
entry('Phleum', 24, la).
entry('Phragimtes', 29, la).
entry('Phyteuma', 93, la).
entry('Picris', 252, la).
entry('Pigfrö', 74, da).
entry('Pigæble', 86, da).
entry('Piil', 306, da).
entry('Piilblad', 302, da).
entry('Pileurt', 138, da).
entry('Pimpinella', 115, la).
entry('Pindsvinknop', 283, da).
entry('Pingvicula', 4, la).
entry('Pinus', 305, la).
entry('Pisum', 247, la).
entry('Plantago', 53, la).
entry('Platanthera', 272, la).
entry('Poa', 34, la).
entry('Polygala', 234, la).
entry('Polygonatum', 132, la).
entry('Polygonum', 138, la).
entry('Poppel', 312, da).
entry('Populus', 312, la).
entry('Pors', 311, da).
entry('Poselæbe', 276, da).
entry('Potamogeton', 65, la).
entry('Potentilla', 183, la).
entry('Pragtstjerne', 166, da).
entry('Prenanthes', 257, la).
entry('Primula', 79, la).
entry('Prunella', 207, la).
entry('Prunus', 172, la).
entry('Pteris', 318, la).
entry('Psyllophora', 285, la).
entry('Pukkellæbe', 276, da).
entry('Pulicaria', 267, la).
entry('Pulmonaria', 73, la).
entry('Pulsatilla', 197, la).
entry('Pyrethrum', 270, la).
entry('Pyrola', 155, la).
entry('Pyrus', 175, la).
entry('Pæretræ', 175, da).
entry('Qvalkved', 119, da).
entry('Qvercus', 304, la).
entry('Qvikgræs', 47, da).
entry('Radax', 15, da).
entry('Radiola', 71, la).
entry('Raigræs', 49, da).
entry('Ranunculus', 191, la).
entry('Rapgræs', 33, da).
entry('Raphanistrum', 221, la).
entry('Raphanus', 221, la).
entry('Rapistrum', 221, la).
entry('Rapunzel', 93, da).
entry('Ravnefod', 217, da).
entry('Regnfand', 263, da).
entry('Remlæbe', 277, da).
entry('Reseda', 171, la).
entry('Rhamnus', 94, la).
entry('Rhynchospora', 15, la).
entry('Ribes', 97, la).
entry('Ribs', 97, da).
entry('Ridderspore', 190, da).
entry('River', 74, da).
entry('Rosa', 176, la).
entry('Rottboellia', 51, la).
entry('Rottehale', 21, da).
entry('Rubia', 61, la).
entry('Rubus', 179, la).
entry('Rundbælle', 236, da).
entry('Rundskulpe', 221, da).
entry('Ruppia', 64, la).
entry('Rævehale', 23, da).
entry('Röllike', 270, da).
entry('Rön', 175, da).
entry('Rörgræs', 25, da).
entry('Rörhvene', 26, da).
entry('Sagina', 170, la).
entry('Sagittaria', 302, la).
entry('Salicornia', 1, la).
entry('Salix', 306, la).
entry('Salsola', 100, la).
entry('Salturt', 1, da).
entry('Sambucus', 119, la).
entry('Samel', 83, da).
entry('Samolus', 83, la).
entry('Sandkryb', 83, da).
entry('Sandvaaner', 163, da).
entry('Sanicula', 118, la).
entry('Sannikel', 118, da).
entry('Saponaria', 160, la).
entry('Sarothamnus', 235, la).
entry('Saxifraga', 157, la).
entry('Scabiosa', 56, la).
entry('Scandix', 109, la).
entry('Schedonorus', 42, la).
entry('Schelhammera', 286, la).
entry('Scheuchzeria', 144, la).
entry('Schoberia', 100, la).
entry('Schoenus', 13, la).
entry('Scirpus', 20, la).
entry('Scleranthus', 157, la).
entry('Scorzonera', 258, la).
entry('Scrophularia', 213, la).
entry('Scutellaria', 208, la).
entry('Sedum', 164, la).
entry('Seglrod', 132, da).
entry('Selinum', 114, la).
entry('Sellerie', 115, da).
entry('Sempervivum', 172, la).
entry('Senebiera', 217, la).
entry('Senecio', 269, la).
entry('Sennep', 226, da).
entry('Serratula', 258, la).
entry('Setaria', 21, la).
entry('Sherardia', 57, la).
entry('Silene', 166, la).
entry('Silybum', 259, la).
entry('Simmer', 197, da).
entry('Sinapis', 226, la).
entry('Sison', 114, la).
entry('Sisymbrium', 225, la).
entry('Sium', 116, la).
entry('Siv', 126, da).
entry('Skarntyde', 112, da).
entry('Skedeknæ', 151, da).
entry('Skjaller', 209, da).
entry('Skjolddrager', 208, da).
entry('Skjælrod', 214, da).
entry('Skjæne', 14, da).
entry('Skjær', 258, da).
entry('Skjærmax', 21, da).
entry('Skjærmlille', 114, da).
entry('Skovstjerne', 146, da).
entry('Skrueax', 277, da).
entry('Skræppe', 110, da).
entry('Slangehoved', 71, da).
entry('Sneglebælle', 241, da).
entry('Sneklokke', 133, da).
entry('Snerle', 83, da).
entry('Snerre', 58, da).
entry('Snylterod', 155, da).
entry('Sodaurt', 100, da).
entry('Solanum', 87, la).
entry('Soldug', 123, da).
entry('Solidago', 268, la).
entry('Solöie', 189, da).
entry('Sonchus', 257, la).
entry('Sorbus', 175, la).
entry('Sparganium', 283, la).
entry('Spartium', 235, la).
entry('Spergella', 169, la).
entry('Spergula', 169, la).
entry('Spidsgab', 52, da).
entry('Spidshale', 51, da).
entry('Spiræa', 174, la).
entry('Spiranthes', 277, la).
entry('Springklap', 222, da).
entry('Springknap', 53, da).
entry('Stachys', 202, la).
entry('Star', 284, da).
entry('Statice', 121, la).
entry('Steenbræk', 157, da).
entry('Steenfrö', 72, da).
entry('Steenklöver', 239, da).
entry('Steenurt', 264, da).
entry('Steffensurt', 3, da).
entry('Stellaria', 161, la).
entry('Stilkax', 46, da).
entry('Stolthendrik', 104, da).
entry('Storkenæb', 227, da).
entry('Stormhat', 190, da).
entry('Strandarve', 163, da).
entry('Strandbo', 302, da).
entry('Strandvaaner', 215, da).
entry('Stratiotes', 313, la).
entry('Succisa', 57, la).
entry('Sumprod', 279, da).
entry('Sumpstraa', 16, da).
entry('Svalerod', 108, da).
entry('Svaleurt', 187, da).
entry('Svinemælk', 257, da).
entry('Svingel', 41, da).
entry('Svovlrod', 112, da).
entry('Sylskulpe', 225, da).
entry('Symphytum', 76, la).
entry('Sæbeurt', 160, da).
entry('Sækbæger', 218, da).
entry('Taarnurt', 222, da).
entry('Tagrör', 29, da).
entry('Takkeklap', 216, da).
entry('Tanacetum', 263, la).
entry('Tandbæger', 205, da).
entry('Tandbælg', 32, da).
entry('Tandrod', 223, da).
entry('Taraxacum', 256, la).
entry('Teesdalia', 216, la).
entry('Teucrium', 207, la).
entry('Thalictrum', 195, la).
entry('Thesium', 99, la).
entry('Thlaspi', 216, la).
entry('Thymus', 205, la).
entry('Thyrsanthus', 83, la).
entry('Tidse', 311, da).
entry('Tidsel', 261, da).
entry('Tidselkugle', 272, da).
entry('Tilia', 189, la).
entry('Timian', 205, da).
entry('Tiniaria', 151, la).
entry('Torilis', 109, la).
entry('Tormentilla', 184, la).
entry('Tornblad', 234, da).
entry('Torskemund', 212, da).
entry('Traadspore', 275, da).
entry('Tragopogon', 258, la).
entry('Tranebær', 147, da).
entry('Tranehals', 227, da).
entry('Trehage', 144, da).
entry('Trichophorum', 18, la).
entry('Trientalis', 146, la).
entry('Trifolium', 236, la).
entry('Triglochin', 144, la).
entry('Triodia', 32, la).
entry('Triticum', 47, la).
entry('Troldurt', 211, da).
entry('Trollius', 198, la).
entry('Tulipa', 134, la).
entry('Turritis', 222, la).
entry('Tusindblad', 303, da).
entry('Tusindfryd', 269, da).
entry('Tusindfrö', 71, da).
entry('Tusindgylden', 89, da).
entry('Tussilago', 263, la).
entry('Tveblad', 171, da).
entry('Tvetand', 203, da).
entry('Typha', 284, la).
entry('Tyltebær', 147, da).
entry('Ulex', 234, la).
entry('Ulmus', 100, la).
entry('Urtica', 302, la).
entry('Utricularia', 4, la).
entry('Vaccinium', 147, la).
entry('Valeriana', 11, la).
entry('Valmue', 168, da).
entry('Vandax', 64, da).
entry('Vandkryber', 138, da).
entry('Vandnavle', 118, da).
entry('Vandstjerne', 282, da).
entry('Vau', 171, da).
entry('Vedbende', 98, da).
entry('Veibred', 53, da).
entry('Verbascum', 84, la).
entry('Verbena', 208, la).
entry('Veronica', 5, la).
entry('Vibefedt', 4, da).
entry('Viburnum', 119, la).
entry('Vicia', 242, la).
entry('Vikke', 242, da).
entry('Vindax', 26, da).
entry('Vinterblomme', 198, da).
entry('Vintergrön', 155, da).
entry('Vinterkarse', 223, da).
entry('Viscaria', 166, la).
entry('Viscum', 310, la).
entry('Volverlei', 267, da).
entry('Vortemælk', 283, da).
entry('Vorterod', 191, da).
entry('Vrietorn', 94, da).
entry('Vulpia', 45, la).
entry('Væselhale', 45, da).
entry('Xanthium', 305, la).
entry('Zannichellia', 282, la).
entry('Zostera', 281, la).
entry('Æl', 301, da).
entry('Ælm', 100, da).
entry('Ærenpriis', 5, da).
entry('Ært', 247, da).
entry('Æselsfoder', 259, da).
entry('Öientröst', 210, da).
entry('Örneöie', 253, da).
